let destinos=[
    "AGUASCALIENTES",
    "ESTADO DE MEXICO",
    "GUANAJUATO",
    "GUERRERO",
    "HIDALGO",
    "JALISCO",
    "MICHOACAN",
    "MORELOS",
    "NAYARIT",
    "NUEVO LEON",
    "PUEBLA",
    "QUERETARO",
    "SAN LUIS POTOSI",
    "SINALOA",
    "TAMAULIPAS",
    "TLAXCALA",
    "ZACATECAS"
];

let ciudades=[
    {estado:'AGUASCALIENTES',ciudad:"AGUASCALIENTES", KM: "229", casetas: "1284"},
    {estado:'AGUASCALIENTES',ciudad:"ASIENTOS", KM: "255", casetas: ""},
    {estado:'AGUASCALIENTES',ciudad:"CALVILLO", KM: "", casetas: ""},
    {estado:'AGUASCALIENTES',ciudad:"EL LLANO", KM: "", casetas: ""},
    {estado:'AGUASCALIENTES',ciudad:"JESUS MARIA", KM: "", casetas: ""},
    {estado:'AGUASCALIENTES',ciudad:"PABELLON DE ARTEAGA", KM: "", casetas: ""},
    {estado:'AGUASCALIENTES',ciudad:"RINCON DE ROMOS", KM: "", casetas: ""},
    {estado:'AGUASCALIENTES',ciudad:"SAN FRANCISCO DE LOS ROMO", KM: "", casetas: ""},
    {estado:'AGUASCALIENTES',ciudad:"TEPEZALA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ACAMBAY", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ACOLMAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ALMOLOYA DE ALQUISIRAS", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ALMOLOYA DE JUAREZ", KM: "169", casetas: "988"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ALMOLOYA DEL RIO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "AMANALCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "AMATEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "AMECAMECA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "APAXCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ATENCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ATIZAPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ATIZAPAN DE ZARAGOZA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ATLACOMULCO", KM: "140", casetas: "772"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ATLAUTLA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "AXAPUSCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "AYAPANGO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CALIMAYA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CAPULHUAC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHALCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHAPA DE MOTA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHAPULTEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHIAUTLA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHICOLOAPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHICONCUAC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHIMALHUACAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CIUDAD DE MEXICO", KM: "218", casetas: "1978"},
    {estado: 'ESTADO DE MEXICO', ciudad: "COACALCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "COATEPEC HARINAS", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "COYOTEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CUAUTITLAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "CUAUTITLAN IZCALLI", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "DONATO GUERRA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ECATEPEC", KM: "", casetas: "1540"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ECATEPEC DE MORELOS", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "EL ORO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "HUEHUETOCA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "HUEYPOXTLA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "IXTAPALUCA", KM: "253", casetas: "1847"},
    {estado: 'ESTADO DE MEXICO', ciudad: "IXTAPAN DE LA SAL", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "IXTAPAN DEL ORO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "IXTLAHUACA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "JILOTEPEC", KM: "170", casetas: "982"},
    {estado: 'ESTADO DE MEXICO', ciudad: "JILOTZINGO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "JIQUIPILCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "JOCOTITLAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "JOQUICINGO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "JUCHITEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "LA PAZ", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "LERMA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "LUVIANOS", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "MELCHOR OCAMPO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "METEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "MIACATLAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "NAUCALPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "NAUCALPAN DE JUAREZ", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "NEZAHUALCOYOTL", KM: "231", casetas: "1778"},
    {estado: 'ESTADO DE MEXICO', ciudad: "NEXTLALPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "NICOLAS ROMERO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "NOPALTEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "OCOYOACAC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "OCUILAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "OTZOLOTEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "OZUMBA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "PAPALOTLA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "POLOTITLAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "QUECHOLAC", KM: "388", casetas: "1866"},
    {estado: 'ESTADO DE MEXICO', ciudad: "RAYON", KM: "199", casetas: "1396"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN ANTONIO LA ISLA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN FELIPE DEL PROGRESO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN JOSE DEL RINCON", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN MARTIN DE LAS PIRAMIDES", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN MATEO ATENCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN SIMON DE GUERRERO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "SANTO TOMAS", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "SOYANIQUILPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "SULTEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TECAMAC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TECAMEX", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEJUPILCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMAMATLA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMASCALAPA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMASCALCINGO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMASCALTEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMOAYA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEOLOYUCAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEOTIHUACAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEPETLAOXTOC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEPETLIXPA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEPOTZOTLAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEQUIXQUIAC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEXCALTITLAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEXCALYACAC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEXCOCO", KM: "248", casetas: "1492"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEZOYUCA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEZUAPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TIANGUISTENCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TIMILPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TLALMANALCO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TLALNEPANTLA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TLATLAYA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TOLUCA", KM: "182", casetas: "988"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TONANITLA", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TONATICO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "TOTOLAPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "VALLE DE BRAVO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "VALLE DE CHALCO SOLIDARIDAD", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "VILLA DE ALLENDE", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "VILLA DEL CARBON", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "XALATLACO", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "XONACATLAN", KM: "189", casetas: "1194"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ZACAZONAPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ZACUALPAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ZINACANTEPEC", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ZUMPAHUACAN", KM: "", casetas: ""},
    {estado: 'ESTADO DE MEXICO', ciudad: "ZUMPANGO", KM: "217", casetas: "2828"},
    {estado: 'GUANAJUATO', ciudad: "ABASOLO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "ACAMBARO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "ALDAMA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "APASEO EL ALTO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "APASEO EL GRANDE", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "CELAYA", KM: "61", casetas: "420"},
    {estado: 'GUANAJUATO', ciudad: "CERANO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "CIUDAD MANUEL DOBLADO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "COMONFORT", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "CORTAZAR", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "CUERAMARO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "DOCTOR MORA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "DOLORES HIDALGO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "DUARTE", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "EL REHILETE", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "EMPALME ESCOBEDO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "FRANCO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "GUANAJUATO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "HUANIMARO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "IRAPUATO", KM: "60", casetas: "454"},
    {estado: 'GUANAJUATO', ciudad: "IRAMUCO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "JARAL DEL PROGRESO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "JERECUARO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "JUVENTINO ROSAS", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "LA ALDEA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "LA CALERA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "LA MONCADA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "LAGUNA DE GUADALUPE", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "LEON", KM: "", casetas: "683"},
    {estado: 'GUANAJUATO', ciudad: "LEON DE LOS ALDAMA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "LOMA PELADA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "LO DE JUAREZ", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "MARFIL", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "MEXICANOS", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "MISION DE CHICHIMECAS", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "MOROLEON", KM: "2", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "NEUTLA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "OCAMPO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "PARACUARO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "PENJAMO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "PRIMERA FRACCION DE CRESPO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "PUENTECILLAS", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "PURISIMA DE BUSTOS", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "RANCHO NUEVO DE LA CRUZ", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "RINCON DE TAMAYO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "RIO GRANDE", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "ROQUE", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "ROMITA", KM: "", casetas: "618"},
    {estado: 'GUANAJUATO', ciudad: "SALAMANCA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SALVATIERRA", KM: "32", casetas: "150"},
    {estado: 'GUANAJUATO', ciudad: "SAN ANTONIO GALLARDO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN BARTOLOME AGUAS CALIENTES", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN BARTOLO DE BERRIOS", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN CRISTOBAL", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN DIEGO DE LA UNION", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN FELIPE", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN FRANCISCO", KM: "124", casetas: "532"},
    {estado: 'GUANAJUATO', ciudad: "SAN FRANCISCO DEL RINCON", KM: "124", casetas: "738"},
    {estado: 'GUANAJUATO', ciudad: "SAN JOSE AGUA AZUL", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN JOSE DE LLANOS", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN JOSE ITURBIDE", KM: "127", casetas: "600"},
    {estado: 'GUANAJUATO', ciudad: "SAN JUAN DE ABAJO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN JUAN DE LA VEGA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN LUIS DE LA PAZ", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN MIGUEL OCTOPAN", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN MIGUEL DE ALLENDE", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN NICOLAS DE LOS AGUSTINOS", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN PEDRO DE LOS NARANJOS", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN RAFAEL DE CERRO GORDO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SAN ROQUE", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SANTA ANA PACUECO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SANTA ROSA PLAN DE AYALA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SANTA TERESA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SANTIAGO DE CUENDA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SARABIA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "SILAO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "TARANDACUAO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "TARIMORO", KM: "46", casetas: "500"},
    {estado: 'GUANAJUATO', ciudad: "TENERIA DEL SANTUARIO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "TIERRA FRIA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "URIANGATO", KM: "", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "URIREO", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "VALLE DE SANTIAGO", KM: "30", casetas: "125"},
    {estado: 'GUANAJUATO', ciudad: "VALTIERRILLA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "VICTORIA DE CORTAZAR", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "VILLAGRAN", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "VILLAS DEL REY", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "YERBABUENA", KM: "", casetas: ""},
    {estado: 'GUANAJUATO', ciudad: "YURIRIA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "ACAPULCO DE JUAREZ", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "ATOYAC DE ALVAREZ", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "AYUTLA DE LOS LIBRES", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "BAJOS DEL EJIDO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "BENITO JUAREZ", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "BUENAVISTA DE CUELLAR", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "CHILAPA DE ALVAREZ", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "CHILPANCINGO DE LOS BRAVO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "COAPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "COCHOAPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "COELLO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "COLOTEPEC", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "COPALA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "COYUCA DE BENITEZ", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "COYUCA DE CATALAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "CRUZ GRANDE", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "CUAJINICUILAPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "CUAUHTEMOC", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "EDUARDO NERI", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "GENERAL CANUTO A. NERI", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "GENERAL HELIODORO CASTILLO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "HUAMUXTITLAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "HUIXTLA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "IXCATEOPAN DE CUAUHTEMOC", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "IZTAPALAPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "JUAN R. ESCUDERO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "LEONARDO BRAVO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "MARQUILLO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "MARTIRES DE TECOANAPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "MOLINO DE SAN VICENTE", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "OMETEPEC", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "PILCAYA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "PETAQUILLAS", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "PETATLAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "QUECHULTENANGO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SAN ISIDRO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SAN JERONIMITO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SAN JOSE DE LAS PILAS", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SAN JUAN BAUTISTA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SAN LUIS ACATLAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SAN LUIS SAN PEDRO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SAN MARCOS", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SAN VICENTE", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SANTA ROSA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SANTIAGO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SANTIAGO DE LA PENA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "SANTIAGO TEPETLAPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TECOCUILCO DE MARCOS PEREZ", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TECOMATLAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TECPAN DE GALEANA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TECPOYOTITLAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TECUALO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TECUANAPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TEPANGO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TEPETITLAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TEPETZINGO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TESORERIA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TEZONAPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TIERRA COLORADA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TIXTLA DE GUERRERO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TLAHUAPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TLALCHICHILPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TLALISTAC", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TLAPEHUALA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TLAXCO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "TOXPA", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "UNIDAD GUERRERO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "XALTENANGO", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "XOCHIHUEHUETLAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "ZACOALPAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "ZIHUATANEJO", KM: "277", casetas: "1511"},
    {estado: 'GUERRERO', ciudad: "ZIHUATANEJO DE AZUETA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ACATLAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ACAXOCHITLAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ACTOPAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "AGUA BLANCA DE ITURBIDE", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "AJACUBA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ALFAJAYUCAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ALMOLOYA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "APAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ATITALAQUIA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ATLAPEXCO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ATOTONILCO DE TULA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ATOTONILCO EL GRANDE", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "CALNALI", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "CARDONAL", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "CHAPANTONGO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "CHAPULHUACAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "CHILCUAUTLA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "CUAUTEPEC", KM: "295", casetas: "1472"},
    {estado: 'HIDALGO', ciudad: "CUAUTEPEC DE HINOJOSA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "EL ARENAL", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ELOXOCHITLAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "EMILIANO ZAPATA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "EPAZOYUCAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "FRANCISCO I. MADERO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "HIDALGO", KM: "178", casetas: "1284"},
    {estado: 'HIDALGO', ciudad: "HUASCA DE OCAMPO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "HUAUTLA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "HUAZALINGO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "HUEHUETLA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "HUEJUTLA DE REYES", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "HUICHAPAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "IXMIQUILPAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "JACALA DE LEDEZMA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "JALTOCAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "JUAREZ HIDALGO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "LA MISION", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "LOLOTLA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "METEPEC", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "METZTITLAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "MINERAL DE LA REFORMA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "MINERAL DEL CHICO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "MINERAL DEL MONTE", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "MIXQUIAHUALA DE JUAREZ", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "MOLANGO DE ESCAMILLA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "NICOLAS FLORES", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "NOPALA DE VILLAGRAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "OMITLAN DE JUAREZ", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "PACHUCA DE SOTO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "PACULA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "PISAFLORES", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "PROGRESO DE OBREGON", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "SAN AGUSTIN METZQUITITLAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "SAN AGUSTIN TLAXIACA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "SAN BARTOLO TUTOTEPEC", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "SAN FELIPE ORIZATLAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "SAN SALVADOR", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "SANTIAGO DE ANAYA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "SANTIAGO TULANTEPEC DE LUGO GUERRERO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "SINGUILUCAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TASQUILLO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TECOZAUTLA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TENANGO DE DORIA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TEPEAPULCO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TEPEHUACAN DE GUERRERO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TEPEJI DEL RIO DE OCAMPO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TEPETITLAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TETEPANGO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TEZONTEPEC DE ALDAMA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TIANGUISTENGO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TIZAYUCA", KM: "230", casetas: "1354"},
    {estado: 'HIDALGO', ciudad: "TLAHUELILPAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TLAHUILTEPA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TLANALAPA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TLANCHINOL", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TLAXCOAPAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TOLCAYUCA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TULA DE ALLENDE", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "TULANCINGO DE BRAVO", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "VILLA DE TEZONTEPEC", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "XOCHIATIPAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "XOCHICOATLAN", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "YAHUALICA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ZACUALTIPAN DE ANGELES", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ZAPOTLAN DE JUAREZ", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ZEMPOALA", KM: "", casetas: ""},
    {estado: 'HIDALGO', ciudad: "ZIMAPAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ACATIC", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ACATLAN DE JUAREZ", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "AHUALULCO DE MERCADO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "AJIJIC", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "AMECA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "AMATITAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ARANDAS", KM: "137", casetas: "203"},
    {estado: 'JALISCO', ciudad: "ATEMAJAC DE BRIZUELA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ATEQUIZA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ATOTLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ATOTONILCO EL ALTO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ATOTONILQUILLO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "AUTLAN DE NAVARRO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "AYOTLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "AYUTLA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "BELLAVISTA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "CAJITITLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "CAMPESTRE LAS PALOMAS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "CAPILLA DE GUADALUPE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "CIMA DEL SOL", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "CIHUATLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "CIUDAD GUZMAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "COLOTLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "COCULA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "COLINAS DEL ROBLE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "COYULA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "CUITZE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "DEGOLLADO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "EL ARENAL", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "EL GRULLO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "EL QUINCE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "EL REFUGIO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "EL SALTO", KM: "214", casetas: "1255"},
    {estado: 'JALISCO', ciudad: "ENCARNACION DE DIAZ", KM: "189", casetas: "1940"},
    {estado: 'JALISCO', ciudad: "GALAXIA BONITO JALISCO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "GALAXIA LA NORIA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "GUADALAJARA", KM: "228", casetas: "1388"},
    {estado: 'JALISCO', ciudad: "HACIENDA SANTA FE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "IXTLAHUACAN DE LOS MEMBRILLOS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "IXTLAHUACAN DEL RIO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "IXTLAPA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "IXTLAHUACAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "IXTAPA", KM: "424", casetas: "3336"},
    {estado: 'JALISCO', ciudad: "JALOSTOTITLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "JAMAY", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "JESUS MARIA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "JOCOTEPEC", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "JUANACATLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "JUCHITLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LA ALAMEDA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LA AURORA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LA BARCA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LA CHONA", KM: "169", casetas: "1219"},
    {estado: 'JALISCO', ciudad: "LA CUCHILLA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LA FORTUNA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LA HUERTA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LA NUEVA ESPERANZA II", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LA RESOLANA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LA RIBERA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LAGOS DE MORENO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LAS JUNTAS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LAS PINTAS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LAS PINTITAS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LOS FRESEROS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LOS GAVILANES", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LOS OLIVOS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "LOS RUISEÑORES", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "MAGDALENA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "MAJALCA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "MAZAMITLA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "MEZCALA DE LA ASUNCION", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "MOCORITO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "OCOTLAN", KM: "169", casetas: "1975"},
    {estado: 'JALISCO', ciudad: "OJUELOS DE JALISCO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "PASEOS DEL VALLE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "PIHUAMO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "PONCITLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "PUENTE GRANDE", KM: "212", casetas: "1458"},
    {estado: 'JALISCO', ciudad: "PUERTO VALLARTA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "QUINTA JESU", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "RANCHO ALEGRE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "REAL DEL VALLE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN AGUSTIN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN ANDRES IXTLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN DIEGO DE ALEJANDRIA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN FRANCISCO DE ASIS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN FRANCISCO DE LA SOLEDAD", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN IGNACIO CERRO GORDO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN JUAN COSALA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN JUAN DE LOS LAGOS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN JUANITO DE ESCOBEDO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN JULIAN", KM: "143", casetas: "562"},
    {estado: 'JALISCO', ciudad: "SAN MARTIN HIDALGO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN MIGUEL CUYUTLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN MIGUEL EL ALTO", KM: "162", casetas: "1124"},
    {estado: 'JALISCO', ciudad: "SAN PATRICIO MELAQUE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN PEDRO ITZICAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN SEBASTIAN DEL SUR", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN SEBASTIAN EL GRANDE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAN VICENTE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SANTA ANA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SANTA ANITA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SANTA CRUZ DE LAS FLORES", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SANTA CRUZ DEL VALLE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "SAYULA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TALA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TALPA DE ALLENDE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TAMAZULA DE GORDIANO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TECALITLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TECOLOTLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TEJUPILCO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TEMATLA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TEOCALTICHE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TEPATITLAN DE MORELOS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TEPITANILLO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TEQUILA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TESISTAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TEUCHITLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TEXCALAMECA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TIZAPAN EL ALTO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TLAJOMULCO DE ZUÑIGA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TLAQUEPAQUE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TLATENANGO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TONALA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TONAYA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TONILA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TOTOLAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "TUXPAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "UNION DE SAN ANTONIO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "UNION DE TULA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "USMAJAC", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "VALLE DE LOS MOLINOS", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "VALLE DORADO INN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "VILLA CORONA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "VILLA HIDALGO", KM: "227", casetas: "1284"},
    {estado: 'JALISCO', ciudad: "VILLA NICOLAS ROMERO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "VILLA PURIFICACION", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "VILLAS DE LA HACIENDA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "XALOSTOC", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "YAHUALICA DE GONZALEZ GALLO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "YAHUALICA", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ZACOALCO DE TORRES", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ZACOALPAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ZACUALPAN", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ZAPOPAN", KM: "235", casetas: "1411"},
    {estado: 'JALISCO', ciudad: "ZAPOTILTIC", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ZAPOTLANEJO", KM: "203", casetas: "1538"},
    {estado: 'JALISCO', ciudad: "ZAPOTE DEL VALLE", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ZITACUARO", KM: "", casetas: ""},
    {estado: 'JALISCO', ciudad: "ZONA SUR", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ACUITZIO DEL CANJE", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "AGUILILLA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "AGUACATE", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "APATZINGAN DE LA CONSTITUCION", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ARIO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ARIO DE RAYON", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ARTEAGA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ALVARO OBREGON", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ANGAHUAN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ANGAMACUTIRO DE LA UNION", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ANTUNEZ", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "BUENOS AIRES", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "BUENAVISTA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "BUENAVISTA TOMATLAN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CARAPAN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CALTZONTZIN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CAPACUARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CAPULA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CHERAN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CHAVINDA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CHILCHOTA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CIUDAD HIDALGO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CIUDAD LAZARO CARDENAS", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "COALCOMAN DE VAZQUEZ PALLARES", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "COAHUAYANA DE HIDALGO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "COJUMATLAN DE REGULES", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "COTIJA DE LA PAZ", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CUANAJO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CUITZEO DEL PORVENIR", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "CUTO DEL PORVENIR", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "FRANCISCO PICHATARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "HEROICA ZITACUARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "HUANDACAREO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "HUETAMO DE NUNEZ", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "IXTLAN DE LOS HERVORES", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "INDAPARAPEO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "JACONA DE PLANCARTE", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "JESUS DEL MONTE (LA CAPILLA)", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "JIQUILPAN", KM: "162", casetas: "818"},
    {estado: 'MICHOACAN', ciudad: "JIQUILPAN DE JUAREZ", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "JOSE SIXTO VERDUZCO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "JUNGAPEO DE JUAREZ", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "LA CANTERA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "LA HUACANA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "LA MIRA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "LA ORILLA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "LA PIEDAD", KM: "94", casetas: "342"},
    {estado: 'MICHOACAN', ciudad: "LAS GUACAMAYAS", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "LOMBARDIA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "LOS REYES DE SALGADO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "MARAVATIO DE OCAMPO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "MARCOS CASTELLANOS", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "MORELIA", KM: "49", casetas: "160"},
    {estado: 'MICHOACAN', ciudad: "MORELOS", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "MADERO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "NAHUATZEN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "NUEVO PARANGARICUTIRO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "NUEVA ITALIA DE LA RUIZ", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "OPOPEO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PAJACUARAN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PANINDICUARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PARACHO DE VERDUZCO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PASTOR ORTIZ", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PERIBAN DE RAMOS", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PATZCUARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PEDERNALES", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PICHATARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PURUARAN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "PUREPERO DE ECHAIZ", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "QUIROGA", KM: "61", casetas: "362"},
    {estado: 'MICHOACAN', ciudad: "QUERENDARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "RINCON DE NICOLAS ROMERO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SALGADO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SALVADOR ESCALANTE", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SAN ANGEL ZURUMUCOPIO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SAN BARTOLO CUITAREO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SAN FRANCISCO PICHATARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SAN JOSE DE GRACIA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SAN JUAN PARANGARICUTIRO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SAN MATIAS GRANDE", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SANTA ANA MAYA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SANTA CLARA DE VALLADARES", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SANTA CLARA DEL COBRE", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SANTA FE DE LA LAGUNA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SANTIAGO TANGAMANDAPIO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "SAHUAYO", KM: "159", casetas: "900"},
    {estado: 'MICHOACAN', ciudad: "TACAMBARO DE CODALLOS", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "TANGAMANDAPIO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "TANGANCICUARO DE ARISTA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "TANCITARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "TARIMBARO", KM: "34", casetas: "160"},
    {estado: 'MICHOACAN', ciudad: "TARETAN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "TINGAMBATO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "TINGUINDIN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "TURICATO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "TUXPAN", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "URUAPAN", KM: "116", casetas: "1468"},
    {estado: 'MICHOACAN', ciudad: "URUAPAN DEL PROGRESO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "VENUSTIANO CARRANZA", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "VILLA MADERO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "VISTA HERMOSA DE NEGRETTE", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "YURECUARO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ZAMORA DE HIDALGO", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ZINAPECUARO DE FIGUEROA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "AMACUZAC", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "ATLATLAHUCAN", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "AXOCHIAPAN", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "AYALA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "COATETELCO", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "COATLAN DEL RIO", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "CUAUTLA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "CUERNAVACA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "EMILIANO ZAPATA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "HUEYAPAN", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "HUITZILAC", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "JANTETELCO", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "JIUTEPEC", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "JOJUTLA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "JONACATEPEC", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "MAZATEPEC", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "MIACATLAN", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "OCUITUCO", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "PUENTE DE IXTLA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TEMIXCO", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TEMOAC", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TEPALCINGO", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TEPOZTLAN", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TETECALA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TETELA DEL VOLCAN", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TLALNEPANTLA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TLALTIZAPAN", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TLAQUILTENANGO", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TLAYACAPAN", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "TOTOLAPAN", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "XOCHITEPEC", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "XOXOCOTLA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "YAUTEPEC", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "YECOPIXTLA", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "ZACATEPEC", KM: "", casetas: ""},
    {estado: 'MORELOS', ciudad: "ZACUALPAN", KM: "", casetas: ""},
    {estado: 'NAYARIT', ciudad: "TEPIC", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "ABASOLO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "AGUALEGUAS", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "ALLENDE", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "ANAHUAC", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "APODACA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "ARAMBERRI", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "BUSTAMANTE", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "CADEREYTA JIMENEZ", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "CARMEN", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "CERRALVO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "CHINA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "CIENEGA DE FLORES", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "DOCTOR ARROYO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "DOCTOR COSS", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "DOCTOR GONZALEZ", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "GALEANA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "GARCIA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "GENERAL BRAVO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "GENERAL ESCOBEDO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "GENERAL TERAN", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "GENERAL TREVIÑO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "GENERAL ZARAGOZA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "GENERAL ZUAZUA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "GUADALUPE", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "HIDALGO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "HIGUERAS", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "HUALAHUISES", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "ITURBIDE", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "JUAREZ", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "LAMPAZOS DE NARANJO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "LEON", KM: "130", casetas: "436"},
    {estado: 'NUEVO LEON', ciudad: "LINARES", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "LOS ALDAMAS", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "LOS HERRERAS", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "LOS RAMONES", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "MARIN", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "MELCHOR OCAMPO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "MIER Y NORIEGA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "MINA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "MONTEMORELOS", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "MONTERREY", KM: "610", casetas: "2692"},
    {estado: 'NUEVO LEON', ciudad: "PARAS", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "PESQUERIA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "RAYONES", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "SABINAS HIDALGO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "SALINAS VICTORIA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "SAN NICOLAS DE LOS GARZA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "SAN PEDRO GARZA GARCIA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "SANTA CATARINA", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "SANTIAGO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "VALLECILLO", KM: "", casetas: ""},
    {estado: 'NUEVO LEON', ciudad: "VILLALDAMA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ACAJETE", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ACATLAN DE OSORIO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ACATZINGO DE HIDALGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ACTIPAN DE MORELOS", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ATEMPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ATENCINGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ATLIXCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ATOLUCA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ATOYATEMPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CASA BLANCA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CHAPULCO", KM: "338", casetas: "1457"},
    {estado: 'PUEBLA', ciudad: "CHIAUTLA DE TAPIA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CHIGNAUTLA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CHOLULA DE RIVADAVIA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CIUDAD DE AJALPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CIUDAD DE CHIGNAHUAPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CIUDAD DE CUETZALAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CIUDAD DE LIBRES", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CIUDAD DE RAFAEL LARA GRAJALES", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CIUDAD DE TLATLAUQUITEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CIUDAD DE ZACATLAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "COXCATLAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CUACNOPALAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CUANALA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "CUAPIAXTLA DE MADERO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "DOMINGO ARENAS", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "EL RINCON CITLALTEPETL", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ESPERANZA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "GUADALUPE VICTORIA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "HEROICA PUEBLA DE ZARAGOZA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "HUAUCHINANGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "HUEJOTZINGO", KM: "307", casetas: "2060"},
    {estado: 'PUEBLA', ciudad: "HUEYAPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "IZUCAR DE MATAMOROS", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "JOLALPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "LA MAGDALENA TETELA MORELOS", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "LA RESURRECCION", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "LOS REYES DE JUAREZ", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "MAGDALENA CUAYUCATEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "NOPALUCAN DE LA GRANJA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "NUEVO NECAXA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ORIENTAL", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "PALMARITO TOCHAPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN AGUSTIN TLAXCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN ANDRES AZUMIATLA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN ANDRES CALPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN ANDRES CHOLULA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN ANTONIO MIHUACAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN BARTOLO TEONTEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN BERNARDINO CHALCHIHUAPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN BERNARDINO TLAXCALANCINGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN BUENAVENTURA NEALTICAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN FELIPE TEOTLALCINGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN FRANCISCO OCOTLAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN GABRIEL CHILAC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN GABRIEL TETZOYOCAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN GREGORIO ZACAPECHPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN HIPOLITO XOCHILTENANGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN JERONIMO COYULA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN JOSE MIAHUATLAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN JUAN CUAUTLANCINGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN JUAN TEPULCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN JUAN TUXCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN JUAN XIUTETELCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN LORENZO ALMECATLA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN LORENZO CHIAUTZINGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN LUCAS EL GRANDE", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN MARCOS TLACOYALCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN MARTIN TEXMELUCAN DE LABASTIDA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN MATEO TLAlXPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN MIGUEL CANOA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN MIGUEL XALTEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN MIGUEL XOXTLA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN NICOLAS DE LOS RANCHOS", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN RAFAEL TLANALAPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN SALVADOR EL SECO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN SALVADOR HUIXCOLOTLA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN SEBASTIAN DE APARICIO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN SEBASTIAN VILLANUEVA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SAN SEBASTIAN ZINACATEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTA ANA XALMIMILULCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTA MARIA COATEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTA MARIA CORONANGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTA MARIA IXTIYUCAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTA MARIA LA ALTA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTA MARIA MOYOTZINGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTA MARIA XONACATEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TLAHUAPAN", KM: "277", casetas: "1302"},
    {estado: 'PUEBLA', ciudad: "SANTA RITA TLAHUAPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTIAGO ACATLAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTIAGO ALSESECA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTIAGO MOMOXPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTIAGO MIAHUATLAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTO TOMAS CHAUTLA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SANTO TOMAS HUEYOTLIPAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "SOLTEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TECALI DE HERRERA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TECAMACHALCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TEHUACAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TENANGO DE LAS FLORES", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TEOTLALCINGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TEOTLALCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TEPATLAXCO DE HIDALGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TEPETZINTLA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TEPEYAHUALCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TEXCALA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TEZIUTLAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TIANGUISMANALCO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TLACHICHUCA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TLACOTEPEC DE BENITO JUAREZ", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TLALTENANGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TLATLAUQUITEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TOCHTEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "TULCINGO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "VENUSTIANO CARRANZA", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "VILLA AVILA CAMACHO", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "VILLA LAZARO CARDENAS", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "XOCHITLAN", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "XONACATEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "YEUALTEPEC", KM: "", casetas: ""},
    {estado: 'PUEBLA', ciudad: "ZARAGOZA", KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "AMEALCO DE BONFIL" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "ARROYO SECO" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "CADEREYTA DE MONTES" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "COLON" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "CORREGIDORA" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "EL MARQUES" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "EZEQUIEL MONTES" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "HUIMILPAN" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "JALPAN DE SERRA" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "LANDA DE MATAMOROS" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "PEDRO ESCOBEDO" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "PENAMILLER" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "PINAL DE AMOLES" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "QUERETARO" , KM: "96", casetas: "612"},
    {estado: "QUERETARO", ciudad: "SAN JOAQUIN" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "SAN JUAN DEL RIO" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "TEQUISQUIAPAN" , KM: "", casetas: ""},
    {estado: "QUERETARO", ciudad: "TOLIMAN" , KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "AHUALULCO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "ALAQUINES", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "AQUISMON", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "ARMADILLO DE LOS INFANTE", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "AXTLA DE TERRAZAS", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "CARDENAS", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "CATORCE", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "CEDRAL", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "CERRITOS", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "CERRO DE SAN PEDRO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "CHARCAS", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "CIUDAD DEL MAIZ", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "CIUDAD FERNANDEZ", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "CIUDAD VALLES", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "COXCATLAN", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "EBANO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "EL NARANJO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "GUADALCAZAR", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "HUEHUETLAN", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "LAGUNILLAS", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "MATEHUALA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "MATLAPA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "MEXQUITIC DE CARMONA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "MOCTEZUMA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "RAYON", KM: "251", casetas: "1500"},
    {estado: 'SAN LUIS POTOSI', ciudad: "RIOVERDE", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SALINAS", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SAN ANTONIO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SAN CIRO DE ACOSTA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SAN LUIS POTOSI", KM: "217", casetas: "458"},
    {estado: 'SAN LUIS POTOSI', ciudad: "SAN MARTIN CHALCHICUAUTLA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SAN NICOLAS TOLENTINO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SANTA CATARINA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SANTA MARIA DEL RIO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SANTO DOMINGO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SAN VICENTE TANCUAYALAB", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "SOLEDAD DE GRACIANO SANCHEZ", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "TAMASOPO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "TAMAZUNCHALE", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "TAMPACAN", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "TAMPAMOLON", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "TAMUIN", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "TANCAHUITZ", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "TANLAJAS", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "TANQUIAN DE ESCOBEDO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "TIERRA NUEVA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "VANEGAS", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "VENADO", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA DE ARISTA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA DE ARRIAGA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA DE GUADALUPE", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA DE LA PAZ", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA DE RAMOS", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA DE REYES", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA HIDALGO", KM: "188", casetas: "1284"},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA JUAREZ", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "XILITLA", KM: "", casetas: ""},
    {estado: 'SAN LUIS POTOSI', ciudad: "ZARAGOZA", KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "AHOME" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "ANGOSTURA" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "BADIRAGUATO" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "CHOIX" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "CONCORDIA" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "COSALA" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "CULIACAN" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "EL FUERTE" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "ELOTA" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "ESCUINAPA" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "GUASAVE" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "MAZATLAN" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "MOCORITO" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "NAVOLATO" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "ROSARIO" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "SALVADOR ALVARADO" , KM: "", casetas: ""},
    {estado: "SINALOA", ciudad: "SAN IGNACIO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "ABASOLO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "ALDAMA" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "ALTAMIRA" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "ANTIGUO MORELOS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "BURGOS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "BUSTAMANTE" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "CAMARGO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "CASAS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "CIUDAD MADERO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "CRUILLAS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "EL MANTE" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "GOMEZ FARIAS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "GONZALEZ" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "GUEMEZ" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "GUERRERO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "GUSTAVO DIAZ ORDAZ" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "HIDALGO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "JAUMAVE" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "JIMENEZ" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "LLERA" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "MAINERO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "MATAMOROS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "MENDEZ" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "MIER" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "MIGUEL ALEMAN" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "MIQUIHUANA" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "NUEVO LAREDO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "NUEVO MORELOS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "OCAMPO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "PADILLA" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "PALMILLAS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "REYNOSA" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "RIO BRAVO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "SAN CARLOS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "SAN FERNANDO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "SAN NICOLAS" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "SOTO LA MARINA" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "TAMPICO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "TULA" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "VALLE HERMOSO" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "VICTORIA" , KM: "449", casetas: "450"},
    {estado: "TAMAULIPAS", ciudad: "VILLAGRAN" , KM: "", casetas: ""},
    {estado: "TAMAULIPAS", ciudad: "XICOTENCATL" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "ACUAMANALA DE MIGUEL HIDALGO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "ALTZAYANCA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "AMAXAC DE GUERRERO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "APETATITLAN DE ANTONIO CARVAJAL" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "APIZACO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "ATLANGATEPEC" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "BENITO JUAREZ" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "CALPULALPAN" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "CHIAUTEMPAN" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "CONTLA DE JUAN CUAMATZI" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "CUAPIAXTLA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "CUAXOMULCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "EL CARMEN TEQUEXQUITLA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "EMILIANO ZAPATA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "ESPAÑITA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "HUAMANTLA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "HUEYOTLIPAN" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "IXTACUIXTLA DE MARIANO MATAMOROS", KM: "", casetas: "" },
    {estado: "TLAXCALA", ciudad: "IXTENCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "LA MAGDALENA TLALTELULCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "LAZARO CARDENAS" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "MAZATECOCHCO DE JOSE MARIA MORELOS" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "MUÑOZ DE DOMINGO ARENAS" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SAN DAMIAN TEXOLOC" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SAN FRANCISCO TETLANOHCAN" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SAN JERONIMO ZACUALPAN" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SAN JOSE TEACALCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SAN JUAN HUACTZINCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SAN LORENZO AXOCOMANITLA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SAN LUCAS TECOPILCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SAN PABLO DEL MONTE" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SANTA ANA NOPALUCAN" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SANTA APOLONIA TEACALCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SANTA CATARINA AYOMETLA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SANTA CRUZ QUILEHTLA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SANTA CRUZ TLAXCALA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "SANTA ISABEL XILOXOXTLA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TENANCINGO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TEOLOCHOLCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TEPETITLA DE LARDIZABAL" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TEPEYANCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TERRENATE" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TETLA DE LA SOLIDARIDAD" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TETLATLAHUCA" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TLAXCALA" , KM: "319", casetas: "2009"},
    {estado: "TLAXCALA", ciudad: "TLAXCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TOCATLAN" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TOTOLAC" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "TZOMPANTEPEC" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "XALOZTOC" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "XALTOCAN" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "XICOHTZINCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "YAUHQUEMECAN" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "ZACATELCO" , KM: "", casetas: ""},
    {estado: "TLAXCALA", ciudad: "ZITLALTEPEC DE TRINIDAD SANCHEZ SANTOS", KM: "", casetas: "" },
    {estado: "ZACATECAS", ciudad: "APOZOL" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "APULCO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "ATOLINGA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "BENITO JUAREZ" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "CALERA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "CAÑITAS DE FELIPE PESCADOR", KM: "", casetas: "" },
    {estado: "ZACATECAS", ciudad: "CHALCHIHUITES" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "CONCEPCION DEL ORO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "CUAUHTEMOC" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "EL PLATEADO DE JOAQUIN AMARO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "EL SALVADOR" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "FRESNILLO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "GENARO CODINA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "GENERAL ENRIQUE ESTRADA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "GENERAL FRANCISCO R. MURGUIA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "GENERAL PANFILO NATERA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "GUADALUPE" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "HUANUSCO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "JALPA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "JEREZ" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "JIMENEZ DEL TEUL" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "JUAN ALDAMA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "JUCHIPILA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "LORETO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "LUIS MOYA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "MAZAPIL" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "MELCHOR OCAMPO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "MEZQUITAL DEL ORO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "MIGUEL AUZA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "MOMAX" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "MONTE ESCOBEDEO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "MORELOS" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "MOYAHUA DE ESTRADA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "NOCHISTLAN DE MEJIA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "NORIA DE ANGELES" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "OJOCALIENTE" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "PANUCO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "PINOS" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "RIO GRANDE" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "SAIN ALTO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "SANTA MARIA DE LA PAZ" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "SOMBRERETE" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "SUSTICACAN" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "TABASCO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "TEPECHITLAN" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "TEPETONGO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "TEUL DE GONZALEZ ORTEGA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "TLALTENANGO DE SANCHEZ ROMAN" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "TRANCOSO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "TRINIDAD GARCIA DE LA CADENA", KM: "", casetas: "" },
    {estado: "ZACATECAS", ciudad: "VALPARAISO", KM: "", casetas: "" },
    {estado: "ZACATECAS", ciudad: "VETAGRANDE" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "VILLA DE COS" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "VILLA GARCIA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "VILLA GONZALEZ ORTEGA" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "VILLA HIDALGO" , KM: "", casetas: ""},
    {estado: "ZACATECAS", ciudad: "VILLANUEVA", KM: "", casetas: "" }
];

document.addEventListener("DOMContentLoaded", (e)=>{
    llenarDestinos();

    document.getElementById('slt1').addEventListener('change', function() {
        actualizarCiudades(this.value);
    });

    document.getElementById('btnPDF').addEventListener('click', (e)=>{
        genPDF();
    });
});

function llenarDestinos(){
    const select = document.getElementById('slt1');
    destinos.forEach(estado => {
        const option = document.createElement('option');
        option.value = estado;
        option.text = estado;
        select.appendChild(option);
    });
    //Cargar las primeras opciones
    actualizarCiudades(document.getElementById('slt1').value);
}

function actualizarCiudades(estadoSeleccionado) {
    
    let selectCiudades = document.getElementById('slt2');
    
    // Limpia las opciones anteriores
    selectCiudades.innerHTML = '';

    // Filtra las ciudades que coinciden con el estado seleccionado
    let ciudadesFiltradas = ciudades.filter(c => c.estado === estadoSeleccionado);

    ciudadesFiltradas.forEach(ciudad => {
        let opcion = document.createElement('option');
        opcion.value = ciudad.ciudad;
        opcion.textContent = ciudad.ciudad;
        selectCiudades.appendChild(opcion);
    });
}

function calcular() {
    let comidas = document.getElementById('txt14');
    let diasS = document.getElementById('txt7');
    let hospedaje = document.getElementById('txt11');
    let combustible = document.getElementById('txt9');
    let casetas = document.getElementById('txt12');
    let vehiculo = document.getElementById('slt');
    let numeroPersonas = parseInt(document.getElementById('txt6').value, 10);
    if (numeroPersonas % 2 != 0) numeroPersonas += 1;
    let fechaInicio = new Date(document.getElementById('txt2').value);
    let fechaFin = new Date(document.getElementById('txt3').value);

    // Calcular comidas
    let diferenciaTiempo = fechaFin - fechaInicio;
    let diasServicio = diferenciaTiempo / (1000 * 60 * 60 * 24);
    diasServicio += 1;
    diasS.value = diasServicio;

    let resultadoComidas = 300 * numeroPersonas * diasServicio;
    comidas.value = resultadoComidas;

    // Calcular el hospedaje
    let resultadoHospedaje = 850 * ((numeroPersonas / 2) * diasServicio);
    hospedaje.value = resultadoHospedaje;

    // Calcular combustible
    let combus = kilometros(casetas);
    let resultadoCombustible = 0;

    
    if (vehiculo.value == "AUTOMÓVIL") {
        resultadoCombustible = combus * (2.0 / 11) * 24 * 1.25;
    }else if (vehiculo.value == "CAMIONETA") {
        resultadoCombustible = combus * (2.0 / 6) * 24 * 1.25;
    }else if (vehiculo.value == "GRÚA") {
        resultadoCombustible = (combus*3) * (2.0 / 4) * 24 * 1.25;
    }
    combustible.value = resultadoCombustible.toFixed(2); // Aseguramos que sea un número con dos decimales

    //Calcular el total
    let total = document.getElementById('txt16');
    let caseta = parseFloat(document.getElementById('txt12').value);
    let adicionales = parseFloat(document.getElementById('txt13').value);
    let manoObra = parseFloat(document.getElementById('txt15').value);
    let IVA = parseFloat(document.getElementById('txtIVA').value);
    total.value = (resultadoComidas + resultadoHospedaje + parseFloat(resultadoCombustible) + caseta + adicionales + manoObra + IVA).toFixed(0);
}

function kilometros(casetasElement) {
    let ciudadS = document.getElementById('slt2').value;
    for (var i = 0; i < ciudades.length; i++) {
        if (ciudades[i].ciudad == ciudadS) {
            casetasElement.value = ciudades[i].casetas;
            return parseInt(ciudades[i].KM, 10); // Aseguramos la base decimal
        }
    }
    return 0;
}

