let destinos=[
    "AGUASCALIENTES",
    "ESTADO DE MEXICO",
    "GUANAJUATO",
    "GUERRERO",
    "HIDALGO",
    "JALISCO",
    "MICHOACAN",
    "MORELOS",
    "NAYARIT",
    "NUEVO LEON",
    "PUEBLA",
    "QUERETARO",
    "SAN LUIS POTOSI",
    "SINALOA",
    "TAMAULIPAS",
    "TLAXCALA",
    "ZACATECAS"
];

let ciudades=[
    {estado:'AGUASCALIENTES',ciudad:"AGUASCALIENTES", KM: "229", casetas: "1284"},
    {estado:'AGUASCALIENTES',ciudad:"ASIENTOS", KM: "340", casetas: "719"},
    {estado:'AGUASCALIENTES',ciudad:"CALVILLO", KM: "308", casetas: "642"},
    {estado:'AGUASCALIENTES',ciudad:"EL LLANO", KM: "270", casetas: "642"},
    {estado:'AGUASCALIENTES',ciudad:"JESUS MARIA", KM: "273", casetas: "642"},
    {estado:'AGUASCALIENTES',ciudad:"PABELLON DE ARTEAGA", KM: "308", casetas: "719"},
    {estado:'AGUASCALIENTES',ciudad:"RINCON DE ROMOS", KM: "316", casetas: "719"},
    {estado:'AGUASCALIENTES',ciudad:"SAN FRANCISCO DE LOS ROMO", KM: "297", casetas: "719"},
    {estado:'AGUASCALIENTES',ciudad:"TEPEZALA", KM: "328", casetas: "719"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ACAMBAY", KM: "189", casetas: "416"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ACOLMAN", KM: "312", casetas: "889"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ALMOLOYA DE ALQUISIRAS", KM: "318", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ALMOLOYA DE JUAREZ", KM: "245", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ALMOLOYA DEL RIO", KM: "274", casetas: "651"},
    {estado: 'ESTADO DE MEXICO', ciudad: "AMANALCO", KM: "344", casetas: "890"},
    {estado: 'ESTADO DE MEXICO', ciudad: "AMATEPEC", KM: "382", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "AMECAMECA", KM: "374", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "APAXCO", KM: "277", casetas: "611"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ATENCO", KM: "261", casetas: "597"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ATIZAPAN", KM: "272", casetas: "651"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ATLACOMULCO", KM: "175", casetas: "286"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ATLAUTLA", KM: "386", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "AXAPUSCO", KM: "337", casetas: "736"},
    {estado: 'ESTADO DE MEXICO', ciudad: "AYAPANGO", KM: "375", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CALIMAYA", KM: "285", casetas: "698"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CAPULHUAC", KM: "271", casetas: "597"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHALCO", KM: "355", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHAPA DE MOTA", KM: "244", casetas: "491"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHAPULTEPEC", KM: "271", casetas: "651"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHIAUTLA", KM: "319", casetas: "889"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHICOLOAPAN", KM: "334", casetas: "942"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHICONCUAC", KM: "317", casetas: "889"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CHIMALHUACAN", KM: "336", casetas: "942"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CIUDAD DE MEXICO", KM: "310", casetas: "783"},
    {estado: 'ESTADO DE MEXICO', ciudad: "COACALCO", KM: "294", casetas: "632"},
    {estado: 'ESTADO DE MEXICO', ciudad: "COATEPEC HARINAS", KM: "334", casetas: "839"},
    {estado: 'ESTADO DE MEXICO', ciudad: "COYOTEPEC", KM: "268", casetas: "574"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CUAUTITLAN", KM: "281", casetas: "608"},
    {estado: 'ESTADO DE MEXICO', ciudad: "CUAUTITLAN IZCALLI", KM: "281", casetas: "608"},
    {estado: 'ESTADO DE MEXICO', ciudad: "DONATO GUERRA", KM: "226", casetas: "315"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ECATEPEC", KM: "299", casetas: "770"},
    {estado: 'ESTADO DE MEXICO', ciudad: "EL ORO DE HIDALGO", KM: "156", casetas: "324"},
    {estado: 'ESTADO DE MEXICO', ciudad: "HUEHUETOCA", KM: "265", casetas: "574"},
    {estado: 'ESTADO DE MEXICO', ciudad: "HUEYPOXTLA", KM: "287", casetas: "626"},
    {estado: 'ESTADO DE MEXICO', ciudad: "IXTAPALUCA", KM: "354", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "IXTAPAN DE LA SAL", KM: "322", casetas: "839"},
    {estado: 'ESTADO DE MEXICO', ciudad: "IXTAPAN DEL ORO", KM: "220", casetas: "262"},
    {estado: 'ESTADO DE MEXICO', ciudad: "IXTLAHUACA", KM: "314", casetas: "661"},
    {estado: 'ESTADO DE MEXICO', ciudad: "EJIDO DE JILOTEPEC", KM: "231", casetas: "491"},
    {estado: 'ESTADO DE MEXICO', ciudad: "JILOTZINGO", KM: "294", casetas: "626"},
    {estado: 'ESTADO DE MEXICO', ciudad: "JIQUIPILCO", KM: "291", casetas: "440"},
    {estado: 'ESTADO DE MEXICO', ciudad: "JOCOTITLAN", KM: "196", casetas: "440"},
    {estado: 'ESTADO DE MEXICO', ciudad: "JOQUICINGO", KM: "301", casetas: "698"},
    {estado: 'ESTADO DE MEXICO', ciudad: "JUCHITEPEC", KM: "374", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "LA PAZ", KM: "330", casetas: "890"},
    {estado: 'ESTADO DE MEXICO', ciudad: "LERMA DE VILLADA", KM: "262", casetas: "597"},
    {estado: 'ESTADO DE MEXICO', ciudad: "VILLA LUVIANOS", KM: "368", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "MELCHOR OCAMPO", KM: "282", casetas: "661"},
    {estado: 'ESTADO DE MEXICO', ciudad: "METEPEC", KM: "266", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ACOLMAN DE NEZAHUALCOYOTL", KM: "312", casetas: "889"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SANTA ANA NEXTLALPAN", KM: "283", casetas: "661"},
    {estado: 'ESTADO DE MEXICO', ciudad: "VILLA NICOLAS ROMERO", KM: "300", casetas: "649"},
    {estado: 'ESTADO DE MEXICO', ciudad: "NOPALTEPEC", KM: "332", casetas: "736"},
    {estado: 'ESTADO DE MEXICO', ciudad: "OCOYOACAC", KM: "264", casetas: "597"},
    {estado: 'ESTADO DE MEXICO', ciudad: "OCUILAN DE ARTEAGA", KM: "305", casetas: "651"},
    {estado: 'ESTADO DE MEXICO', ciudad: "OZUMBA DE ALZATE", KM: "386", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "PAPALOTLA", KM: "322", casetas: "889"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN ANTONIO POLOTITLAN", KM: "213", casetas: "480"},
    {estado: 'ESTADO DE MEXICO', ciudad: "IXTLAHUACA DE RAYON", KM: "205", casetas: "440"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN ANTONIO LA ISLA", KM: "277", casetas: "698"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN FELIPE DEL PROGRESO", KM: "189", casetas: "386"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN JOSE DEL RINCON", KM: "173", casetas: "262"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN MARTIN DE LAS PIRAMIDES", KM: "323", casetas: "889"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN MATEO ATENCO", KM: "261", casetas: "597"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN SIMON DE GUERRERO", KM: "328", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SANTO TOMAS", KM: "281", casetas: "608"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SOYANIQUILPAN", KM: "231", casetas: "506"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SULTEPEC", KM: "323", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TECAMAC", KM: "304", casetas: "661"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEJUPILCO", KM: "345", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMAMATLA", KM: "361", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMASCALAPA", KM: "319", casetas: "681"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMASCALCINGO", KM: "162", casetas: "324"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMASCALTEPEC", KM: "314", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEMOAYA", KM: "244", casetas: "494"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEOLOYUCAN", KM: "279", casetas: "608"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEOTIHUACAN DE ARISTA", KM: "320", casetas: "889"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEPETLAOXTOC", KM: "338", casetas: "890"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEPETLIXPA", KM: "387", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEPOTZOTLAN", KM: "275", casetas: "608"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEQUIXQUIAC", KM: "286", casetas: "611"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEXCALTITLAN", KM: "309", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN MATEO TEXCALYACAC", KM: "278", casetas: "651"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEXCOCO", KM: "327", casetas: "890"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TEZOYUCA", KM: "314", casetas: "889"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SANTIAGO TIANGUISTENCO", KM: "273", casetas: "651"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TIMILPAN", KM: "201", casetas: "416"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TLALMANALCO", KM: "365", casetas: "1054"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TLALNEPANTLA", KM: "294", casetas: "608"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TLATLAYA", KM: "395", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TOLUCA", KM: "240", casetas: "494"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SANTA MARIA TONANITLA", KM: "289", casetas: "661"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TONATICO", KM: "328", casetas: "839"},
    {estado: 'ESTADO DE MEXICO', ciudad: "TOTOLAPAN", KM: "349", casetas: "890"},
    {estado: 'ESTADO DE MEXICO', ciudad: "VALLE DE BRAVO", KM: "286", casetas: "791"},
    {estado: 'ESTADO DE MEXICO', ciudad: "VALLE DE CHALCO SOLIDARIDAD", KM: "332", casetas: "770"},
    {estado: 'ESTADO DE MEXICO', ciudad: "VILLA DE ALLENDE", KM: "217", casetas: "315"},
    {estado: 'ESTADO DE MEXICO', ciudad: "VILLA DEL CARBON", KM: "230", casetas: "386"},
    {estado: 'ESTADO DE MEXICO', ciudad: "XALATLACO", KM: "282", casetas: "651"},
    {estado: 'ESTADO DE MEXICO', ciudad: "XONACATLAN", KM: "249", casetas: "559"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ZACAZONAPAN", KM: "342", casetas: "791"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ZACUALPAN", KM: "369", casetas: "839"},
    {estado: 'ESTADO DE MEXICO', ciudad: "SAN MIGUEL ZINACANTEPEC", KM: "252", casetas: "539"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ZUMPAHUACAN", KM: "324", casetas: "698"},
    {estado: 'ESTADO DE MEXICO', ciudad: "ZUMPANGO DE OCAMPO", KM: "286", casetas: "661"},
    {estado: 'GUANAJUATO', ciudad: "ABASOLO", KM: "113", casetas: "203"},
    {estado: 'GUANAJUATO', ciudad: "ACAMBARO", KM: "89", casetas: "174"},
    {estado: 'GUANAJUATO', ciudad: "ALDAMA", KM: "93", casetas: "218"},
    {estado: 'GUANAJUATO', ciudad: "APASEO EL ALTO", KM: "116", casetas: "210"},
    {estado: 'GUANAJUATO', ciudad: "APASEO EL GRANDE", KM: "105", casetas: "210"},
    {estado: 'GUANAJUATO', ciudad: "CELAYA", KM: "94", casetas: "210"},
    {estado: 'GUANAJUATO', ciudad: "CERANO", KM: "27", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "MANUEL DOBLADO", KM: "208", casetas: "369"},
    {estado: 'GUANAJUATO', ciudad: "COMONFORT", KM: "111", casetas: "210"},
    {estado: 'GUANAJUATO', ciudad: "CORTAZAR", KM: "74", casetas: "155"},
    {estado: 'GUANAJUATO', ciudad: "CUERAMARO", KM: "126", casetas: "203"},
    {estado: 'GUANAJUATO', ciudad: "DOCTOR MORA", KM: "207", casetas: "300"},
    {estado: 'GUANAJUATO', ciudad: "DOLORES HIDALGO", KM: "180", casetas: "218"},
    {estado: 'GUANAJUATO', ciudad: "DUARTE", KM: "147", casetas: "333"},
    {estado: 'GUANAJUATO', ciudad: "EMPALME ESCOBEDO", KM: "105", casetas: "210"},
    {estado: 'GUANAJUATO', ciudad: "FRANCO", KM: "116", casetas: "218"},
    {estado: 'GUANAJUATO', ciudad: "GUANAJUATO", KM: "123", casetas: "218"},
    {estado: 'GUANAJUATO', ciudad: "HUANIMARO", KM: "72", casetas: "90"},
    {estado: 'GUANAJUATO', ciudad: "IRAPUATO", KM: "82", casetas: "203"},
    {estado: 'GUANAJUATO', ciudad: "IRAMUCO", KM: "37", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "JARAL DEL PROGRESO", KM: "41", casetas: "90"},
    {estado: 'GUANAJUATO', ciudad: "JERECUARO", KM: "120", casetas: "174"},
    {estado: 'GUANAJUATO', ciudad: "JUVENTINO ROSAS", KM: "83", casetas: "210"},
    {estado: 'GUANAJUATO', ciudad: "LA ALDEA", KM: "120", casetas: "264"},
    {estado: 'GUANAJUATO', ciudad: "LEON", KM: "130", casetas: "683"},
    {estado: 'GUANAJUATO', ciudad: "MARFIL", KM: "119", casetas: "218"},
    {estado: 'GUANAJUATO', ciudad: "MOROLEON", KM: "2", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "OCAMPO", KM: "214", casetas: "218"},
    {estado: 'GUANAJUATO', ciudad: "ROMITA", KM: "118", casetas: "264"},
    {estado: 'GUANAJUATO', ciudad: "SALAMANCA", KM: "59", casetas: "155"},
    {estado: 'GUANAJUATO', ciudad: "SALVATIERRA", KM: "39", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "SAN FRANCISCO", KM: "133", casetas: "218"},
    {estado: 'GUANAJUATO', ciudad: "SAN FRANCISCO DEL RINCON", KM: "162", casetas: "369"},
    {estado: 'GUANAJUATO', ciudad: "SAN JOSE AGUA AZUL", KM: "110", casetas: "210"},
    {estado: 'GUANAJUATO', ciudad: "SAN JOSE DE LLANOS", KM: "97", casetas: "218"},
    {estado: 'GUANAJUATO', ciudad: "SAN JOSE ITURBIDE", KM: "186", casetas: "300"},
    {estado: 'GUANAJUATO', ciudad: "SAN ROQUE", KM: "91", casetas: "203"},
    {estado: 'GUANAJUATO', ciudad: "SILAO", KM: "113", casetas: "218"},
    {estado: 'GUANAJUATO', ciudad: "TARIMORO", KM: "57", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "URIANGATO", KM: "1", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "URIREO", KM: "44", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "VALLE DE SANTIAGO", KM: "37", casetas: "90"},
    {estado: 'GUANAJUATO', ciudad: "VALTIERRILLA", KM: "51", casetas: "0"},
    {estado: 'GUANAJUATO', ciudad: "VICTORIA DE CORTAZAR", KM: "48", casetas: "90"},
    {estado: 'GUANAJUATO', ciudad: "YURIRIA", KM: "10", casetas: "0"},
    {estado: 'GUERRERO', ciudad: "ACAPULCO", KM: "645", casetas: "1526"},
    {estado: 'GUERRERO', ciudad: "ATOYAC DE ALVAREZ", KM: "559", casetas: "832"},
    {estado: 'GUERRERO', ciudad: "AYUTLA DE LOS LIBRES", KM: "674", casetas: "1200"},
    {estado: 'GUERRERO', ciudad: "BAJOS DEL EJIDO", KM: "659", casetas: "1407"},
    {estado: 'GUERRERO', ciudad: "CUAUHTEMOC", KM: "422", casetas: "857"},
    {estado: 'GUERRERO', ciudad: "IZTAPALAPA", KM: "328", casetas: "847"},
    {estado: 'GUERRERO', ciudad: "PILCAYA", KM: "342", casetas: "839"},
    {estado: 'GUERRERO', ciudad: "PETAQUILLAS", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "PETATLAN", KM: "", casetas: ""},
    {estado: 'GUERRERO', ciudad: "QUECHULTENANGO", KM: "552", casetas: "1027"},
    {estado: 'GUERRERO', ciudad: "SAN ISIDRO", KM: "625", casetas: "1200"},
    {estado: 'GUERRERO', ciudad: "SAN JERONIMITO", KM: "423", casetas: "787"},
    {estado: 'GUERRERO', ciudad: "SAN JUAN BAUTISTA Coapala", KM: "695", casetas: "1057"},
    {estado: 'GUERRERO', ciudad: "SAN LUIS ACATLAN", KM: "810", casetas: "1546"},
    {estado: 'GUERRERO', ciudad: "SAN LUIS SAN PEDRO", KM: "501", casetas: "787"},
    {estado: 'GUERRERO', ciudad: "SAN MARCOS", KM: "698", casetas: "1546"},
    {estado: 'GUERRERO', ciudad: "SAN VICENTE", KM: "572", casetas: "1027"},
    {estado: 'GUERRERO', ciudad: "SANTA ROSA", KM: "650", casetas: "1200"},
    {estado: 'GUERRERO', ciudad: "EL SANTIAGO", KM: "858", casetas: "1546"},
    {estado: 'GUERRERO', ciudad: "TECOMATLAN", KM: "463", casetas: "981"},
    {estado: 'GUERRERO', ciudad: "TECPAN DE GALEANA", KM: "535", casetas: "832"},
    {estado: 'GUERRERO', ciudad: "TEPANGO", KM: "682", casetas: "1200"},
    {estado: 'GUERRERO', ciudad: "TEPETITLAN", KM: "528", casetas: "912"},
    {estado: 'GUERRERO', ciudad: "TIXTLA DE GUERRERO", KM: "559", casetas: "1027"},
    {estado: 'GUERRERO', ciudad: "TLAHUAPA", KM: "706", casetas: "986"},
    {estado: 'GUERRERO', ciudad: "TLAPEHUALA", KM: "334", casetas: "80"},
    {estado: 'GUERRERO', ciudad: "TLAXCO", KM: "540", casetas: "912"},
    {estado: 'GUERRERO', ciudad: "ZACOALPAN", KM: "843", casetas: "1546"},
    {estado: 'GUERRERO', ciudad: "ZIHUATANEJO", KM: "401", casetas: "787"},
    {estado: 'HIDALGO', ciudad: "ACATLAN", KM: "376", casetas: "736"},
    {estado: 'HIDALGO', ciudad: "ACAXOCHITLAN", KM: "394", casetas: "772"},
    {estado: 'HIDALGO', ciudad: "ACTOPAN", KM: "300", casetas: "581"},
    {estado: 'HIDALGO', ciudad: "AGUA BLANCA DE ITURBIDE", KM: "416", casetas: "772"},
    {estado: 'HIDALGO', ciudad: "AJACUBA", KM: "273", casetas: "596"},
    {estado: 'HIDALGO', ciudad: "ALFAJAYUCAN", KM: "270", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "ALMOLOYA", KM: "374", casetas: "806"},
    {estado: 'HIDALGO', ciudad: "APAN", KM: "369", casetas: "806"},
    {estado: 'HIDALGO', ciudad: "ATITALAQUIA", KM: "260", casetas: "596"},
    {estado: 'HIDALGO', ciudad: "ATLAPEXCO", KM: "557", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "ATOTONILCO DE TULA", KM: "268", casetas: "596"},
    {estado: 'HIDALGO', ciudad: "ATOTONILCO EL GRANDE", KM: "363", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "CALNALI", KM: "496", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "CARDONAL", KM: "261", casetas: "596"},
    {estado: 'HIDALGO', ciudad: "CHAPANTONGO", KM: "258", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "CHAPULHUACAN", KM: "436", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "CHILCUAUTLA", KM: "288", casetas: "581"},
    {estado: 'HIDALGO', ciudad: "CUAUTEPEC DE HINOJOSA", KM: "379", casetas: "736"},
    {estado: 'HIDALGO', ciudad: "EL ARENAL", KM: "306", casetas: "581"},
    {estado: 'HIDALGO', ciudad: "ELOXOCHITLAN", KM: "471", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "EMILIANO ZAPATA", KM: "359", casetas: "806"},
    {estado: 'HIDALGO', ciudad: "EPAZOYUCAN", KM: "346", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "FRANCISCO I. MADERO", KM: "311", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "HIDALGO", KM: "428", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "HUASCA DE OCAMPO", KM: "360", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "HUAUTLA", KM: "566", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "HUAZALINGO", KM: "517", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "HUEHUETLA", KM: "472", casetas: "772"},
    {estado: 'HIDALGO', ciudad: "HUEJUTLA DE REYES", KM: "545", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "HUICHAPAN", KM: "231", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "IXMIQUILPAN", KM: "282", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "JACALA", KM: "373", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "JALTOCAN", KM: "558", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "JUAREZ HIDALGO", KM: "477", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "LA MISION", KM: "395", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "LOLOTLA", KM: "467", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "METEPEC", KM: "397", casetas: "772"},
    {estado: 'HIDALGO', ciudad: "METZTITLAN", KM: "417", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "MINERAL DE LA REFORMA", KM: "335", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "MINERAL DEL CHICO", KM: "351", casetas: "682"},
    {estado: 'HIDALGO', ciudad: "MINERAL DEL MONTE", KM: "342", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "MIXQUIAHUALA DE JUAREZ", KM: "269", casetas: "581"},
    {estado: 'HIDALGO', ciudad: "MOLANGO", KM: "460", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "NICOLAS FLORES", KM: "329", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "NOPALA", KM: "230", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "OMITLAN DE JUAREZ", KM: "349", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "PACHUCA", KM: "325", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "PACULA", KM: "363", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "PISAFLORES", KM: "439", casetas: "378"},
    {estado: 'HIDALGO', ciudad: "SAN SALVADOR", KM: "300", casetas: "581"},
    {estado: 'HIDALGO', ciudad: "TEPEAPULCO", KM: "346", casetas: "771"},
    {estado: 'HIDALGO', ciudad: "TETEPANGO", KM: "269", casetas: "596"},
    {estado: 'HIDALGO', ciudad: "TIZAYUCA", KM: "316", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "XOCHIATIPAN", KM: "588", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "YAHUALICA", KM: "568", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "ZACUALTIPAN", KM: "427", casetas: "681"},
    {estado: 'HIDALGO', ciudad: "ZEMPOALA", KM: "335", casetas: "736"},
    {estado: 'HIDALGO', ciudad: "ZIMAPAN", KM: "313", casetas: "378"},
    {estado: 'JALISCO', ciudad: "AYOTLAN", KM: "217", casetas: "277"},
    {estado: 'JALISCO', ciudad: "AYUTLA", KM: "446", casetas: "893"},
    {estado: 'JALISCO', ciudad: "CIHUATLAN", KM: "617", casetas: "1279"},
    {estado: 'JALISCO', ciudad: "CIUDAD GUZMAN", KM: "418", casetas: "1086"},
    {estado: 'JALISCO', ciudad: "COLOTLAN", KM: "526", casetas: "763"},
    {estado: 'JALISCO', ciudad: "EL SALTO", KM: "288", casetas: "704"},
    {estado: 'JALISCO', ciudad: "ENCARNACION DE DIAZ", KM: "221", casetas: "642"},
    {estado: 'JALISCO', ciudad: "GALAXIA LA NORIA", KM: "319", casetas: "782"},
    {estado: 'JALISCO', ciudad: "GUADALAJARA", KM: "304", casetas: "694"},
    {estado: 'JALISCO', ciudad: "IXTAPA", KM: "624", casetas: "2044"},
    {estado: 'JALISCO', ciudad: "LA ALAMEDA", KM: "303", casetas: "782"},
    {estado: 'JALISCO', ciudad: "LA CHONA", KM: "217", casetas: "482"},
    {estado: 'JALISCO', ciudad: "LA CUCHILLA", KM: "313", casetas: "694"},
    {estado: 'JALISCO', ciudad: "LA FORTUNA", KM: "328", casetas: "782"},
    {estado: 'JALISCO', ciudad: "LA HUERTA", KM: "543", casetas: "893"},
    {estado: 'JALISCO', ciudad: "LAS PINTAS", KM: "296", casetas: "694"},
    {estado: 'JALISCO', ciudad: "LOS FRESEROS", KM: "286", casetas: "782"},
    {estado: 'JALISCO', ciudad: "LOS GAVILANES", KM: "311", casetas: "694"},
    {estado: 'JALISCO', ciudad: "LOS OLIVOS", KM: "297", casetas: "782"},
    {estado: 'JALISCO', ciudad: "LOS RUISEÑORES", KM: "343", casetas: "694"},
    {estado: 'JALISCO', ciudad: "MAGDALENA", KM: "405", casetas: "1164"},
    {estado: 'JALISCO', ciudad: "OCOTLAN", KM: "228", casetas: "507"},
    {estado: 'JALISCO', ciudad: "PUENTE GRANDE", KM: "278", casetas: "704"},
    {estado: 'JALISCO', ciudad: "SAN AGUSTIN", KM: "314", casetas: "694"},
    {estado: 'JALISCO', ciudad: "SAN JULIAN", KM: "202", casetas: "369"},
    {estado: 'JALISCO', ciudad: "SAN MIGUEL EL ALTO", KM: "252", casetas: "562"},
    {estado: 'JALISCO', ciudad: "SAN VICENTE", KM: "217", casetas: "444"},
    {estado: 'JALISCO', ciudad: "SAYULA", KM: "404", casetas: "1086"},
    {estado: 'JALISCO', ciudad: "TEQUILA", KM: "395", casetas: "1169"},
    {estado: 'JALISCO', ciudad: "ZAPOPAN", KM: "307", casetas: "694"},
    {estado: 'JALISCO', ciudad: "ZAPOTLANEJO", KM: "270", casetas: "704"},
    {estado: 'JALISCO', ciudad: "ZITACUARO", KM: "212", casetas: "482"},
    {estado: 'MICHOACAN', ciudad: "ACUITZIO DEL CANJE", KM: "93", casetas: "80"},
    {estado: 'MICHOACAN', ciudad: "AGUILILLA", KM: "317", casetas: "515"},
    {estado: 'MICHOACAN', ciudad: "AGUACATE", KM: "333", casetas: "515"},
    {estado: 'MICHOACAN', ciudad: "APATZINGAN DE LA CONSTITUCION", KM: "", casetas: ""},
    {estado: 'MICHOACAN', ciudad: "ARIO DE RAYON", KM: "187", casetas: "444"},
    {estado: 'MICHOACAN', ciudad: "ARTEAGA", KM: "328", casetas: "651"},
    {estado: 'MICHOACAN', ciudad: "ALVARO OBREGON", KM: "55", casetas: "104"},
    {estado: 'MICHOACAN', ciudad: "ANGAHUAN", KM: "194", casetas: "367"},
    {estado: 'MICHOACAN', ciudad: "ANGAMACUTIRO", KM: "127", casetas: "234"},
    {estado: 'MICHOACAN', ciudad: "ANTUNEZ", KM: "220", casetas: "515"},
    {estado: 'MICHOACAN', ciudad: "BUENOS AIRES", KM: "372", casetas: "852"},
    {estado: 'MICHOACAN', ciudad: "BUENAVISTA", KM: "134", casetas: "262"},
    {estado: 'MICHOACAN', ciudad: "BUENAVISTA TOMATLAN", KM: "269", casetas: "515"},
    {estado: 'MICHOACAN', ciudad: "CARAPAN", KM: "153", casetas: "234"},
    {estado: 'MICHOACAN', ciudad: "CALTZONTZIN", KM: "154", casetas: "367"},
    {estado: 'MICHOACAN', ciudad: "CAPACUARO", KM: "177", casetas: "367"},
    {estado: 'MICHOACAN', ciudad: "CAPULA", KM: "74", casetas: "181"},
    {estado: 'MICHOACAN', ciudad: "CHERAN", KM: "179", casetas: "234"},
    {estado: 'MICHOACAN', ciudad: "CHAVINDA", KM: "223", casetas: "444"},
    {estado: 'MICHOACAN', ciudad: "CHILCHOTA", KM: "162", casetas: "234"},
    {estado: 'MICHOACAN', ciudad: "CIUDAD HIDALGO", KM: "133", casetas: "262"},
    {estado: 'MICHOACAN', ciudad: "HUANDACAREO", KM: "28", casetas: "0"},
    {estado: 'MICHOACAN', ciudad: "LA PIEDAD", KM: "168", casetas: "218"},
    {estado: 'MICHOACAN', ciudad: "LAS GUACAMAYAS", KM: "369", casetas: "852"},
    {estado: 'MICHOACAN', ciudad: "LOMBARDIA", KM: "192", casetas: "461"},
    {estado: 'MICHOACAN', ciudad: "LOS REYES DE SALGADO", KM: "229", casetas: "367"},
    {estado: 'MICHOACAN', ciudad: "MARAVATIO", KM: "110", casetas: "262"},
    {estado: 'MICHOACAN', ciudad: "MORELIA", KM: "49", casetas: "160"},
    {estado: 'MICHOACAN', ciudad: "MORELOS", KM: "70", casetas: "80"},
    {estado: 'MICHOACAN', ciudad: "PATZCUARO", KM: "108", casetas: "253"},
    {estado: 'MICHOACAN', ciudad: "QUIROGA", KM: "93", casetas: "181"},
    {estado: 'MICHOACAN', ciudad: "TANGAMANDAPIO", KM: "217", casetas: "444"},
    {estado: 'MICHOACAN', ciudad: "TARIMBARO", KM: "45", casetas: "80"},
    {estado: 'MICHOACAN', ciudad: "URUAPAN", KM: "158", casetas: "367"},
    {estado: 'MORELOS', ciudad: "TEMIXCO", KM: "346", casetas: "651"},
    {estado: 'MORELOS', ciudad: "TEPALCINGO", KM: "442", casetas: "986"},
    {estado: 'MORELOS', ciudad: "TLALTIZAPAN", KM: "377", casetas: "680"},
    {estado: 'MORELOS', ciudad: "TLAQUILTENANGO", KM: "419", casetas: "839"},
    {estado: 'MORELOS', ciudad: "TLAYACAPAN", KM: "405", casetas: "986"},
    {estado: 'MORELOS', ciudad: "TOTOLAPAN", KM: "411", casetas: "1114"},
    {estado: 'MORELOS', ciudad: "XOCHITEPEC", KM: "356", casetas: "680"},
    {estado: 'MORELOS', ciudad: "XOXOCOTLA", KM: "368", casetas: "713"},
    {estado: 'MORELOS', ciudad: "YAUTEPEC", KM: "398", casetas: "986"},
    {estado: 'MORELOS', ciudad: "YECAPIXTLA", KM: "415", casetas: "986"},
    {estado: 'MORELOS', ciudad: "ZACATEPEC", KM: "410", casetas: "986"},
    {estado: 'MORELOS', ciudad: "ZACUALPAN", KM: "384", casetas: "839"},
    {estado: 'NAYARIT', ciudad: "TEPIC", KM: "535", casetas: "1627"},
    {estado: 'NUEVO LEON', ciudad: "ABASOLO", KM: "794", casetas: "885"},
    {estado: 'NUEVO LEON', ciudad: "ALLENDE", KM: "755", casetas: "457"},
    {estado: 'NUEVO LEON', ciudad: "ANAHUAC", KM: "1041", casetas: "1329"},
    {estado: 'NUEVO LEON', ciudad: "GUADALUPE", KM: "780", casetas: "717"},
    {estado: 'NUEVO LEON', ciudad: "HIDALGO", KM: "799", casetas: "885"},
    {estado: 'NUEVO LEON', ciudad: "HIGUERAS", KM: "829", casetas: "957"},
    {estado: 'NUEVO LEON', ciudad: "LINARES", KM: "683", casetas: "457"},
    {estado: 'NUEVO LEON', ciudad: "LOS HERRERAS", KM: "909", casetas: "1293"},
    {estado: 'NUEVO LEON', ciudad: "LOS RAMONES", KM: "868", casetas: "1218"}, 
    {estado: 'NUEVO LEON', ciudad: "MONTEMORELOS", KM: "734", casetas: "457"},
    {estado: 'NUEVO LEON', ciudad: "MONTERREY", KM: "775", casetas: "717"},
    {estado: 'NUEVO LEON', ciudad: "RAYONES", KM: "651", casetas: "457"},
    {estado: 'NUEVO LEON', ciudad: "SANTIAGO", KM: "809", casetas: "717"},
    {estado: 'PUEBLA', ciudad: "ACAJETE", KM: "459", casetas: "1129"},
    {estado: 'PUEBLA', ciudad: "ACATLAN DE OSORIO", KM: "555", casetas: "986"},
    {estado: 'PUEBLA', ciudad: "ACATZINGO", KM: "475", casetas: "1170"},
    {estado: 'PUEBLA', ciudad: "ACTIPAN DE MORELOS", KM: "475", casetas: "1170"},
    {estado: 'PUEBLA', ciudad: "ATEMPAN", KM: "531", casetas: "1083"},
    {estado: 'PUEBLA', ciudad: "ATENCINGO", KM: "474", casetas: "986"},
    {estado: 'PUEBLA', ciudad: "ATLIXCO", KM: "458", casetas: "1058"},
    {estado: 'PUEBLA', ciudad: "ATOLUCA", KM: "549", casetas: "1089"},
    {estado: 'PUEBLA', ciudad: "ATOYATEMPAN", KM: "486", casetas: "1170"},
    {estado: 'PUEBLA', ciudad: "CASA BLANCA", KM: "443", casetas: "1086"},
    {estado: 'PUEBLA', ciudad: "CHAPULCO", KM: "569", casetas: "1222"},
    {estado: 'PUEBLA', ciudad: "COXCATLAN", KM: "602", casetas: "1222"},
    {estado: 'PUEBLA', ciudad: "CUACNOPALAN", KM: "514", casetas: "1170"},
    {estado: 'PUEBLA', ciudad: "CUANALA", KM: "426", casetas: "1002"},
    {estado: 'PUEBLA', ciudad: "HUEJOTZINGO", KM: "411", casetas: "971"},
    {estado: 'PUEBLA', ciudad: "IZUCAR DE MATAMOROS", KM: "469", casetas: "986"},
    {estado: 'PUEBLA', ciudad: "JOLALPAN", KM: "486", casetas: "986"},
    {estado: 'PUEBLA', ciudad: "LA RESURRECCION", KM: "442", casetas: "1086"},
    {estado: 'PUEBLA', ciudad: "LOS REYES DE JUAREZ", KM: "478", casetas: "1170"},
    {estado: 'PUEBLA', ciudad: "NUEVO NECAXA", KM: "423", casetas: "841"},
    {estado: 'PUEBLA', ciudad: "PALMARITO TOCHAPAN", KM: "496", casetas: "1170"},
    {estado: 'PUEBLA', ciudad: "NUEVO TLAHUAPAN", KM: "407", casetas: "1210"},
    {estado: 'PUEBLA', ciudad: "SAN FELIPE TEOTLALCINGO", KM: "410", casetas: "971"},
    {estado: 'PUEBLA', ciudad: "TEOTLALCO", KM: "463", casetas: "986"},
    {estado: 'PUEBLA', ciudad: "TEXCAL", KM: "505", casetas: "977"},
    {estado: 'PUEBLA', ciudad: "TULCINGO", KM: "570", casetas: "986"},
    {estado: 'PUEBLA', ciudad: "VENUSTIANO CARRANZA", KM: "492", casetas: "931"},
    {estado: 'PUEBLA', ciudad: "XOCHITLAN", KM: "510", casetas: "1170"},
    {estado: 'PUEBLA', ciudad: "ZARAGOZA", KM: "517", casetas: "1044"},
    {estado: "QUERETARO", ciudad: "AMEALCO DE BONFIL" , KM: "166", casetas: "174"},
    {estado: "QUERETARO", ciudad: "ARROYO SECO" , KM: "417", casetas: "306"},
    {estado: "QUERETARO", ciudad: "CADEREYTA DE MONTES" , KM: "237", casetas: "306"},
    {estado: "QUERETARO", ciudad: "COLON" , KM: "194", casetas: "306"},
    {estado: "QUERETARO", ciudad: "CORREGIDORA" , KM: "156", casetas: "306"},
    {estado: "QUERETARO", ciudad: "EZEQUIEL MONTES" , KM: "225", casetas: "306"},
    {estado: "QUERETARO", ciudad: "HUIMILPAN" , KM: "159", casetas: "318"},
    {estado: "QUERETARO", ciudad: "JALPAN DE SERRA" , KM: "368", casetas: "306"},
    {estado: "QUERETARO", ciudad: "PEÑAMILLER" , KM: "307", casetas: "306"},
    {estado: "QUERETARO", ciudad: "PINAL DE AMOLES" , KM: "329", casetas: "306"},
    {estado: "QUERETARO", ciudad: "QUERETARO" , KM: "138", casetas: "306"},
    {estado: "QUERETARO", ciudad: "SAN JOAQUIN" , KM: "300", casetas: "306"},
    {estado: "QUERETARO", ciudad: "SAN JUAN DEL RIO" , KM: "191", casetas: "306"},
    {estado: "QUERETARO", ciudad: "TEQUISQUIAPAN" , KM: "210", casetas: "306"},
    {estado: "QUERETARO", ciudad: "TOLIMAN" , KM: "219", casetas: "306"},
    {estado: 'SAN LUIS POTOSI', ciudad: "AHUALULCO DEL SONIDO", KM: "368", casetas: "690"},
    {estado: 'SAN LUIS POTOSI', ciudad: "ALAQUINES", KM: "506", casetas: "612"},
    {estado: 'SAN LUIS POTOSI', ciudad: "CARDENAS", KM: "488", casetas: "612"},
    {estado: 'SAN LUIS POTOSI', ciudad: "CEDRAL", KM: "483", casetas: "457"},
    {estado: 'SAN LUIS POTOSI', ciudad: "CERRITOS", KM: "370", casetas: "480"},
    {estado: 'SAN LUIS POTOSI', ciudad: "CHARCAS", KM: "460", casetas: "690"},
    {estado: 'SAN LUIS POTOSI', ciudad: "CIUDAD VALLES", KM: "552", casetas: "847"},
    {estado: 'SAN LUIS POTOSI', ciudad: "COXCATLAN", KM: "489", casetas: "306"},
    {estado: 'SAN LUIS POTOSI', ciudad: "EBANO", KM: "633", casetas: "963"},
    {estado: 'SAN LUIS POTOSI', ciudad: "EL NARANJO", KM: "522", casetas: "557"},
    {estado: 'SAN LUIS POTOSI', ciudad: "LAGUNILLAS", KM: "438", casetas: "306"},
    {estado: 'SAN LUIS POTOSI', ciudad: "MOCTEZUMA", KM: "417", casetas: "690"},
    {estado: 'SAN LUIS POTOSI', ciudad: "RAYON", KM: "473", casetas: "612"},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA DE REYES", KM: "231", casetas: "218"},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA HIDALGO", KM: "312", casetas: "418"},
    {estado: 'SAN LUIS POTOSI', ciudad: "VILLA JUAREZ", KM: "379", casetas: "612"},
    {estado: 'SAN LUIS POTOSI', ciudad: "XILITLA", KM: "451", casetas: "306"},
    {estado: 'SAN LUIS POTOSI', ciudad: "ZARAGOZA", KM: "528", casetas: "457"},
    {estado: "SINALOA", ciudad: "AHOME" , KM: "1239", casetas: "3387"},
    {estado: "SINALOA", ciudad: "ANGOSTURA" , KM: "1114", casetas: "3361"},
    {estado: "SINALOA", ciudad: "BADIRAGUATO" , KM: "1096", casetas: "3154"},
    {estado: "SINALOA", ciudad: "CHOIX" , KM: "1337", casetas: "3387"},
    {estado: "SINALOA", ciudad: "CONCORDIA" , KM: "801", casetas: "2723"},
    {estado: "SINALOA", ciudad: "COSALA" , KM: "976", casetas: "2923"},
    {estado: "SINALOA", ciudad: "CULIACAN" , KM: "1018", casetas: "3128"},
    {estado: "SINALOA", ciudad: "EL FUERTE" , KM: "1288", casetas: "3387"},
    {estado: "SINALOA", ciudad: "ELOTA" , KM: "897", casetas: "2743"},
    {estado: "SINALOA", ciudad: "ESCUINAPA" , KM: "723", casetas: "2446"},
    {estado: "SINALOA", ciudad: "GUASAVE" , KM: "1155", casetas: "3387"},
    {estado: "SINALOA", ciudad: "MAZATLAN" , KM: "816", casetas: "2743"},
    {estado: "SINALOA", ciudad: "MOCORITO" , KM: "1136", casetas: "3361"},
    {estado: "SINALOA", ciudad: "NAVOLATO" , KM: "1033", casetas: "3175"},
    {estado: "SINALOA", ciudad: "EL ROSARIO" , KM: "744", casetas: "2561"},
    {estado: "SINALOA", ciudad: "SALVADOR ALVARADO" , KM: "1028", casetas: "3175"},
    {estado: "SINALOA", ciudad: "SAN IGNACIO" , KM: "902", casetas: "2743"},
    {estado: "TAMAULIPAS", ciudad: "ABASOLO" , KM: "715", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "ALDAMA" , KM: "825", casetas: "1506"},
    {estado: "TAMAULIPAS", ciudad: "ALTAMIRA" , KM: "732", casetas: "1506"},
    {estado: "TAMAULIPAS", ciudad: "ANTIGUO MORELOS" , KM: "554", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "BURGOS" , KM: "820", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "BUSTAMANTE" , KM: "517", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "CAMARGO" , KM: "974", casetas: "974"},
    {estado: "TAMAULIPAS", ciudad: "CASAS" , KM: "625", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "HIDALGO" , KM: "681", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "VILLA MAINERO" , KM: "721", casetas: "457"},
    {estado: "TAMAULIPAS", ciudad: "MATAMOROS" , KM: "1099", casetas: "1634"},
    {estado: "TAMAULIPAS", ciudad: "NUEVO LAREDO" , KM: "982", casetas: "1329"},
    {estado: "TAMAULIPAS", ciudad: "NUEVO MORELOS" , KM: "535", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "OCAMPO" , KM: "511", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "NUEVO PADILLA" , KM: "426", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "PALMILLAS" , KM: "500", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "REYNOSA" , KM: "1026", casetas: "1486"},
    {estado: "TAMAULIPAS", ciudad: "RIO BRAVO" , KM: "1042", casetas: "1539"},
    {estado: "TAMAULIPAS", ciudad: "TAMPICO" , KM: "699", casetas: "1492"},
    {estado: "TAMAULIPAS", ciudad: "TULA" , KM: "458", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "VICTORIA" , KM: "596", casetas: "557"},
    {estado: "TAMAULIPAS", ciudad: "VILLAGRAN" , KM: "709", casetas: "557"},
    {estado: "TLAXCALA", ciudad: "ACUAMANALA" , KM: "432", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "AMAXAC DE GUERRERO" , KM: "425", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "APETATITLAN" , KM: "422", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "APIZACO" , KM: "412", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "ATLANGATEPEC" , KM: "408", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "BENITO JUAREZ" , KM: "376", casetas: "806"},
    {estado: "TLAXCALA", ciudad: "CALPULALPAN" , KM: "358", casetas: "806"},
    {estado: "TLAXCALA", ciudad: "CHIAUTEMPAN" , KM: "423", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "CONTLA" , KM: "425", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "CUAPIAXTLA" , KM: "456", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "CUAXOMULCO" , KM: "418", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "TEQUEXQUITLA" , KM: "467", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "EMILIANO ZAPATA" , KM: "452", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "ESPAÑITA" , KM: "378", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "HUAMANTLA" , KM: "438", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "HUEYOTLIPAN" , KM: "382", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "IXTENCO" , KM: "446", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "LA MAGDALENA TLALTELULCO" , KM: "426", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "LAZARO CARDENAS" , KM: "441", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "MAZATECOCHCO" , KM: "438", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "MUÑOZ" , KM: "400", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "TENANCINGO" , KM: "439", casetas: "1086"},
    {estado: "TLAXCALA", ciudad: "TEOLOCHOLCO" , KM: "430", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "TEPETITLA" , KM: "402", casetas: "971"},
    {estado: "TLAXCALA", ciudad: "TEPEYANCO" , KM: "424", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "TERRENATE" , KM: "441", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "TLAXCALA" , KM: "420", casetas: "1047"},
    {estado: "TLAXCALA", ciudad: "TLAXCO" , KM: "435", casetas: "851"},
    {estado: "TLAXCALA", ciudad: "TOCATLAN" , KM: "425", casetas: "851"},
    {estado: "ZACATECAS", ciudad: "APOZOL" , KM: "380", casetas: "642"},
    {estado: "ZACATECAS", ciudad: "APULCO" , KM: "296", casetas: "642"},
    {estado: "ZACATECAS", ciudad: "ATOLINGA" , KM: "443", casetas: "642"},
    {estado: "ZACATECAS", ciudad: "BENITO JUAREZ" , KM: "575", casetas: "891"},
    {estado: "ZACATECAS", ciudad: "SAN ANTONIO DE LA CALERA" , KM: "415", casetas: "642"},
    {estado: "ZACATECAS", ciudad: "CAÑITAS", KM: "518", casetas: "891" },
    {estado: "ZACATECAS", ciudad: "CHALCHIHUITES" , KM: "605", casetas: "891"},
    {estado: "ZACATECAS", ciudad: "CONCEPCION DEL ORO" , KM: "649", casetas: "821"},
    {estado: "ZACATECAS", ciudad: "CUAUHTEMOC" , KM: "560", casetas: "891"},
    {estado: "ZACATECAS", ciudad: "EL PLATEADO DE JOAQUIN AMARO" , KM: "405", casetas: "642"},
    {estado: "ZACATECAS", ciudad: "EL SALVADOR" , KM: "722", casetas: "821"},
    {estado: "ZACATECAS", ciudad: "FRESNILLO" , KM: "452", casetas: "869"},
    {estado: "ZACATECAS", ciudad: "JALPA" , KM: "351", casetas: "642"},
    {estado: "ZACATECAS", ciudad: "JEREZ DE GARCIA SALINAS" , KM: "452", casetas: "763"},
    {estado: "ZACATECAS", ciudad: "LORETO" , KM: "327", casetas: "642"},
    {estado: "ZACATECAS", ciudad: "MONTE ESCOBEDEO" , KM: "537", casetas: "763"},
    {estado: "ZACATECAS", ciudad: "MORELOS" , KM: "405", casetas: "821"},
    {estado: "ZACATECAS", ciudad: "NORIA DE ANGELES" , KM: "353", casetas: "642"},
    {estado: "ZACATECAS", ciudad: "PINOS" , KM: "326", casetas: "613"},
    {estado: "ZACATECAS", ciudad: "RIO GRANDE" , KM: "530", casetas: "891"},
    {estado: "ZACATECAS", ciudad: "SAIN ALTO" , KM: "514", casetas: "891"},
    {estado: "ZACATECAS", ciudad: "TABASCO" , KM: "376", casetas: "642"},
    {estado: "ZACATECAS", ciudad: "TEPETONGO" , KM: "481", casetas: "763"},
    {estado: "ZACATECAS", ciudad: "VILLA HIDALGO" , KM: "342", casetas: "613"},
    {estado: "ZACATECAS", ciudad: "VILLANUEVA", KM: "459", casetas: "763" }
];

document.addEventListener("DOMContentLoaded", (e)=>{
    llenarDestinos();

    document.getElementById('slt1').addEventListener('change', function() {
        actualizarCiudades(this.value);
    });

    document.getElementById('btnPDF').addEventListener('click', (e)=>{
        genPDF();
    });
});

function llenarDestinos(){
    const select = document.getElementById('slt1');
    destinos.forEach(estado => {
        const option = document.createElement('option');
        option.value = estado;
        option.text = estado;
        select.appendChild(option);
    });
    //Cargar las primeras opciones
    actualizarCiudades(document.getElementById('slt1').value);
}

function actualizarCiudades(estadoSeleccionado) {
    
    let selectCiudades = document.getElementById('slt2');
    
    // Limpia las opciones anteriores
    selectCiudades.innerHTML = '';

    // Filtra las ciudades que coinciden con el estado seleccionado
    let ciudadesFiltradas = ciudades.filter(c => c.estado === estadoSeleccionado);

    ciudadesFiltradas.forEach(ciudad => {
        let opcion = document.createElement('option');
        opcion.value = ciudad.ciudad;
        opcion.textContent = ciudad.ciudad;
        selectCiudades.appendChild(opcion);
    });
}

function calcular() {
    let comidas = document.getElementById('txt14');
    let diasS = document.getElementById('txt7');
    let hospedaje = document.getElementById('txt11');
    let combustible = document.getElementById('txt9');
    let casetas = document.getElementById('txt12');
    let vehiculo = document.getElementById('slt');
    let numeroPersonas = parseInt(document.getElementById('txt6').value, 10);
    let fechaInicio = new Date(document.getElementById('txt2').value);
    let fechaFin = new Date(document.getElementById('txt3').value);

    // Calcular comidas
    let diferenciaTiempo = fechaFin - fechaInicio;
    let diasServicio = diferenciaTiempo / (1000 * 60 * 60 * 24);
    diasServicio += 1;
    diasS.value = diasServicio;

    let resultadoComidas = 300 * numeroPersonas * diasServicio;
    comidas.value = resultadoComidas;

    // Calcular el hospedaje
    let resultadoHospedaje;
    if(diasServicio>1){
    if (numeroPersonas % 2 != 0) numeroPersonas += 1;
    resultadoHospedaje = 850 * ((numeroPersonas / 2) * (diasServicio-1));
    hospedaje.value = resultadoHospedaje;
    }else {
        resultadoHospedaje=0;
        hospedaje.value = resultadoHospedaje;
    }

    // Calcular combustible
    let combus = kilometros(casetas);
    let resultadoCombustible = 0;

    
    if (vehiculo.value == "AUTOMÓVIL") {
        resultadoCombustible = combus * (2.0 / 11) * 24 * 1.25;
    }else if (vehiculo.value == "CAMIONETA") {
        resultadoCombustible = combus * (2.0 / 6) * 24 * 1.25;
    }else if (vehiculo.value == "GRÚA") {
        resultadoCombustible = ((combus*3) * (2.0 / 4) * 24 * 1.25)*1.25;
    }
    combustible.value = resultadoCombustible.toFixed(2); // Aseguramos que sea un número con dos decimales

    //Calcular el total
    let total = document.getElementById('txt16');
    let caseta = parseFloat(document.getElementById('txt12').value);
    let adicionales = parseFloat(document.getElementById('txt13').value);
    let manoObra = parseFloat(document.getElementById('txt15').value);
    let IVA = parseFloat(document.getElementById('txtIVA').value);
    let subtotal = resultadoComidas + resultadoHospedaje + parseFloat(resultadoCombustible) + caseta + adicionales + manoObra;
    total.value = (resultadoComidas + resultadoHospedaje + parseFloat(resultadoCombustible) + caseta + adicionales + manoObra + IVA).toFixed(0);

    // Calcular IVA en caso de que se requiera factura
    let checkbox = document.getElementById('cbo1');

    if (checkbox.checked) {
        let IVAc = subtotal * 0.16;
        document.getElementById('txtIVA').value = IVAc.toFixed(2);
        subtotal += IVAc;
        total.value = subtotal.toFixed(2);
    }
}

function kilometros(casetasElement) {
    let ciudadS = document.getElementById('slt2').value;
    console.log(ciudadS);
    for (var i = 0; i < ciudades.length; i++) {
        if (ciudades[i].ciudad == ciudadS) {
            casetasElement.value = (ciudades[i].casetas*1.25);
            return parseInt(ciudades[i].KM, 10); // Aseguramos la base decimal
        }
    }
    return 0;
}